name: 'Sail Deploy'
description: 'Deploy your site to DigitalOcean via Sail'
inputs:
  passphrase:
    description: 'The GPG passphrase used to encrypt the .sail archive'
  encrypted_filename:
    description: 'The .sail encrypted archive filename, usually .sail.tar.gz.gpg'
    default: '.sail.tar.gz.gpg'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install sailed.io
    - shell: bash
      env:
        SAIL_PASSPHRASE: ${{ inputs.passphrase }}
        SAIL_FILENAME: ${{ inputs.encrypted_filename }}
      run: |
        gpg --quiet --yes --batch -d --passphrase=$SAIL_PASSPHRASE $SAIL_FILENAME | tar xzf -
        sail --version
        sail deploy
